#pragma once

#include <cstdint>
#include <vector>

#include "core_keeloq.h"

namespace esphome {
namespace jarolift {

static constexpr uint8_t NUM_CHANNELS = 16;

// Button codes of the TDEF protocol (upper nibble of the 64-bit word).
enum Button : uint8_t {
  BUTTON_LEARN_OLD = 0x1,
  BUTTON_DOWN = 0x2,
  BUTTON_STOP = 0x4,
  BUTTON_UP = 0x8,
  BUTTON_UP_DOWN = 0xA,
};

// One 72-bit telegram: 64 bits sent LSB first, then the high discrimination byte LSB first.
struct Frame {
  uint64_t data;
  uint8_t disc_high;
};

// Serial of a channel, as generated by the old dongle's cmd_generate_serials().
inline uint32_t channel_serial(uint32_t prefix, uint8_t channel) { return (prefix << 8) + channel; }

// Builds a telegram addressed to the channels in `channel_mask` (bit n = channel n), like
// dewenni's JaroliftController: the discrimination value carries the mask and the low byte of the
// serial.
Frame build_frame_mask(const KeeloqKey &master, uint32_t serial, uint16_t channel_mask, uint8_t button,
                       uint16_t counter);

// A single channel, exactly like the old dongle's keygen() / keeloq() / radio_tx().
inline Frame build_frame(const KeeloqKey &master, uint32_t serial, uint8_t channel, uint8_t button,
                         uint16_t counter) {
  return build_frame_mask(master, serial, uint16_t(1u << channel), button, counter);
}

// Level on the TX pin and how long it is held. LOW keys the carrier.
struct Pulse {
  bool level;
  uint32_t duration_us;
};

// Pin sequence for one telegram repeated `repetitions` times, with the old dongle's timing:
// 1150 us lead-in, 13 preamble pulses (400/380 us), 3.5 ms gap, 72 bits of 1200 us, 16 ms pause.
std::vector<Pulse> frame_pulses(const Frame &frame, int repetitions);

// Raw bit fields of a received telegram.
struct RawTelegram {
  uint32_t hopcode;
  uint32_t serial;  // 28 bits on air
  uint8_t button;
  uint8_t disc_high;
};

struct DecodedTelegram {
  uint32_t serial;
  uint8_t button;
  uint16_t counter;
  uint16_t channel_mask;  // bit n = channel n
};

// Decrypts a received telegram. Returns false if the discrimination check fails
// (wrong key or corrupted bits).
bool decode_telegram(const RawTelegram &raw, const KeeloqKey &master, DecodedTelegram *out);

// Edge-driven receiver for the RX pin (HIGH = carrier). Interrupt-safe: fixed buffers, no allocation.
class RxDecoder {
 public:
  static constexpr uint32_t SYNC_MIN_US = 3650;
  static constexpr uint32_t SYNC_MAX_US = 4300;
  static constexpr uint32_t BIT_MIN_US = 300;
  static constexpr uint32_t BIT_MAX_US = 1000;
  static constexpr uint32_t BIT_THRESHOLD_US = 600;
  static constexpr int BITS = 72;

  // Call on every edge with the new pin level and a microsecond timestamp.
  void on_edge(bool level, uint32_t now_us);
  // Returns true once and fills `out` when a complete telegram was captured.
  bool poll(RawTelegram *out);

 private:
  uint32_t last_edge_us_{0};
  bool synced_{false};
  int count_{0};
  uint8_t bits_[BITS / 8]{};
  volatile bool ready_{false};
  RawTelegram frame_{};
};

}  // namespace jarolift
}  // namespace esphome
